version: "3.4"

#docker stack deploy -c tty-2f24a0dc49.yml tty-2f24a0dc49
services:
  tty-2f24a0dc49:
    image: "jlpz/gotty:2.0.0-alpha.3-tmux"
    #image: "jlpz/gotty:1.0.1-tmux"
    #command: ["-p", "8080", "--permit-write","--reconnect", "tmux", "new", "-A", "-s", "gotty", "/bin/sh"]
    ports:
      - "50001:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        constraints: [node.role == worker]
      update_config:
        delay: 2s
      labels:
        - "traefik.backend=tty-2f24a0dc49"
        - "traefik.frontend.rule=Host: tty-2f24a0dc49.it-dojo.io, "
        - "traefik.docker.network=traefik_external"
        - "traefik.port=8080"
    networks:
      - traefik_external

networks:
  traefik_external:
    external: true
