version: "3.4"

services:
  mongodb:
    image: aashreys/mongo-auth:latest
    volumes:
      - "{{docker_containers_volume_path}}/api/mongodb/data:/data/db:Z"
    #ports:
      #- "27017:27017"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
      placement:
        constraints: [node.role == worker]
    networks:
      - internal
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=admin
      - MONGODB_APPLICATION_DATABASE=it-dojo-backend-api
      - MONGODB_APPLICATION_USER=it-dojo-backend-api
      - MONGODB_APPLICATION_PASS=it-dojo-backend-api

  it-dojo-backend-api:
    image: "{{api_image}}"
    ports:
      - "{{api_tcp_port}}:5000"
    depends_on:
      - mongodb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - "{{docker_containers_volume_path}}/api/bin/tty-controller:/usr/bin/tty-controller:Z"
      - "{{docker_containers_volume_path}}/api/templates/:/templates/:Z"
    working_dir: "/usr/src/app"
    deploy:
{% if api_mode is defined %}{% if api_mode[0] == 'replicated' %}
      replicas: {{api_mode[1]|default("1")}}
{% else %}
      mode: global
{% endif %}{% endif %}
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        constraints: [node.role == manager]
      update_config:
        delay: 2s
      labels:
        - "traefik.backend=it-dojo-backend-api"
        - "traefik.frontend.rule=Host: {% for subdomain in api_subdomains %}{{subdomain}}.{{domain}}, {% endfor %}"
        - "traefik.docker.network=traefik_external"
        - "traefik.port=5000"
    networks:
      - internal
      - traefik_external
    environment:
      - LANG=C.UTF-8
      - FLASK_APP=run.py
      - SMTP_USER=postmaster@it-dojo.com
      - SMTP_PASSWD=you-will-never-guess

networks:
  traefik_external:
    external: true
  internal:
    driver: overlay
