- name: create compose config folder
  file: path={{docker_compose_path}} mode=755 state=directory

- name: create service docker volume directories
  file: path={{docker_containers_volume_path}}/{{item}} state=directory
  with_items:
    - echo/data

- name: capture docker volume directories
  set_fact: docker_containers_volume_paths="{{docker_containers_volume_paths|default([])}} + ['{{docker_containers_volume_path}}/{{item}}']"
  with_items:
    - echo/data

- debug: var=docker_containers_volume_paths

- name: create echo compose template
  template: src=echo.yml dest={{docker_compose_path}}/echo.yml
  register: compose_template

- name: deploy echo stack
  command: docker stack deploy -c {{docker_compose_path}}/echo.yml echo
  register: echo_exec
  when:
    - inventory_hostname == docker_swarm_primary_manager
    - compose_template.changed

- debug: var=echo_exec
