version: "3.4"

services:
  registry:
    image: "{{registry_image}}"
    ports:
      - "{{registry_tcp_port}}:5000"
    volumes:
      - {{docker_containers_volume_path}}/registry/data:/var/lib/registry
    deploy:
{% if registry_mode is defined %}{% if registry_mode[0] == 'replicated' %}
      replicas: {{registry_mode[1]|default("1")}}
{% else %}
      mode: global
{% endif %}{% endif %}
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        constraints: [node.role == worker]
      update_config:
        delay: 2s
      labels:
        - "traefik.backend=registry"
        - "traefik.frontend.rule=Host: {% for subdomain in registry_subdomains %}{{subdomain}}.{{domain}}, {% endfor %}"
        - "traefik.docker.network=traefik_external"
        - "traefik.port=5000"
    networks:
      - traefik_external
    #logging:
      #driver: syslog
      #options:
        #syslog-facility: local2 #as defined at roles/docker/templates/rsyslog.docker.conf
        #tag: "docker/{% raw %}{{.Name}}{% endraw %}"

networks:
  traefik_external:
    external: true
