---
- name: install nginx
  apt: name={{item}} state=present install_recommends=no update_cache=yes cache_valid_time=86400
  with_items:
  - nginx

#- name: configure nginx
  #template: src=nginx.cfg.j2 dest=/etc/nginx/nginx.cfg
  #notify: restart nginx

- name: enable nginx
  systemd: name=nginx enabled=yes

- name: ensure nginx is running
  service: name=nginx enabled=yes state=started

- name: upload default index.html
  template: src=index.html.j2 dest=/var/www/html/index.html
